# Generated by Django 5.2.5 on 2025-08-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the recipe", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the recipe"),
                ),
                (
                    "recipe_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image of the recipe",
                        null=True,
                        upload_to="recipes/",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Recipe Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Recipe updated"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this recipe",
                        limit_choices_to={"user_type": "seller"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
    ]
